### ISSUE TITLE
Can not get fullscreen window.

### ISSUE THREAD

**Issue by clort81** [maemo-leste/libsdl#1]
I haven't been able to get fullscreen windows with SDL on leste + droid4.

I would like to get fullscreen windows.  This will disable compositing and halve the 100% CPU load caused to Xorg.

**Comment by clort81** [comment]
Can get fullscreen now and have submitted to ML the fixes to avoid the half-screen display shift problem.

Two libsdl1.2 issues remain. I will open one for each.

**Comment by MerlijnWajer** [comment]
Where are the exact patches? I did check the mailing but only found a post where you mailed a patch, but then later said it wasn't a full/proper fix. Thanks!
